# SPDX-License-Identifier: GPL-2.0-only
"""Compile tools/datestamp/datestamp.c and write core/src/fw/aspect/datestamp-code.ts.

The module is position independent (-fropi -frwpi, no global data, every address passed in through
its context argument), so the bytes do not depend on where they are placed. This is checked by
linking it at two addresses and comparing. Compiler: clang if present, else `python3 -m ziglang cc`
(pip install ziglang; set GRMOD_ZIG=1 to use it even when clang is installed); flags as for the ratio modules (cortex-a9, ARM, soft float, -Os, no library).
"""
import base64
import hashlib
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
SRC = HERE / 'datestamp.c'
OUT = ROOT / 'core' / 'src' / 'fw' / 'aspect' / 'datestamp-code.ts'
USE_ZIG = bool(os.environ.get('GRMOD_ZIG')) or not (shutil.which('clang') and shutil.which('ld.lld') and shutil.which('llvm-objcopy'))
FLAGS = ['-mcpu=cortex_a9' if USE_ZIG else '-mcpu=cortex-a9', '-marm', '-mfloat-abi=soft', '-Os',
         '-ffreestanding', '-fno-builtin', '-fno-unwind-tables', '-fno-asynchronous-unwind-tables', '-nostdlib',
         '-fropi', '-frwpi', '-fno-jump-tables', '-Wall', '-Wextra', '-Werror']


def tools():
    if not USE_ZIG:
        return ['clang', '-target', 'armv7-none-eabi'], ['ld.lld'], ['llvm-objcopy']
    z = [sys.executable, '-m', 'ziglang']
    return z + ['cc', '-target', 'arm-freestanding-eabi'], z + ['ld.lld'], z + ['objcopy']


def run(cmd):
    r = subprocess.run([str(c) for c in cmd], capture_output=True, text=True)
    if r.returncode:
        sys.exit(f'{" ".join(map(str, cmd))}\n{r.stdout}{r.stderr}')
    return r.stdout


def build(cc, ld, objcopy, tmp, origin, extra=()):
    obj = tmp / 'ds.o'
    run(cc + FLAGS + list(extra) + ['-c', SRC, '-o', obj])
    elf = tmp / f'ds_{origin:x}.elf'
    run(ld + [f'-Ttext=0x{origin:x}', '--entry=datestamp', '-o', elf, obj])
    out = tmp / f'ds_{origin:x}.bin'
    run(objcopy + ['-O', 'binary', '-j', '.text', elf, out])
    sections = run(['readelf', '-S', '-W', elf])
    for name in ('.data', '.bss', '.rodata', '.got'):
        if f' {name} ' in sections or f' {name}.' in sections:
            sys.exit(f'module has a {name} section')
    symbols = run(['readelf', '-s', '-W', elf])
    entry = [l for l in symbols.splitlines() if l.strip().endswith(' datestamp')]
    if not entry or int(entry[0].split()[1], 16) != origin:
        sys.exit('datestamp is not at the start of .text')
    return out.read_bytes()


def main():
    cc, ld, objcopy = tools()
    with tempfile.TemporaryDirectory() as t:
        tmp = Path(t)
        a = build(cc, ld, objcopy, tmp, 0x10000)
        b = build(cc, ld, objcopy, tmp, 0x543f0000)
        da = build(cc, ld, objcopy, tmp, 0x10000, ['-DDIAG'])
        db = build(cc, ld, objcopy, tmp, 0x543f0000, ['-DDIAG'])
    if a != b or da != db:
        sys.exit('module is not position independent')
    while len(a) % 4:
        a += b'\0'
    while len(da) % 4:
        da += b'\0'
    version = run(cc + ['--version']).splitlines()[0]
    src_hash = hashlib.sha256(SRC.read_bytes()).hexdigest()
    OUT.write_text(
        '// SPDX-License-Identifier: GPL-2.0-only\n'
        '// GENERATED by tools/datestamp/gen.py from tools/datestamp/datestamp.c -- do not edit.\n'
        f'// Compiler: {version}\n'
        f'// Source SHA-256: {src_hash}\n'
        '// Position independent: entry `datestamp(ctx, config)` at offset 0.\n\n'
        f"export const DATESTAMP_CODE = '{base64.b64encode(a).decode()}';\n"
        f'export const DATESTAMP_CODE_LENGTH = {len(a)};\n'
        '/** Test builds only (-DDIAG): also prints the encoder configuration on the 720x480 picture. */\n'
        f"export const DATESTAMP_DIAG_CODE = '{base64.b64encode(da).decode()}';\n"
        f"export const DATESTAMP_SOURCE_SHA256 = '{src_hash}';\n")
    print(f'{OUT}: {len(a)} bytes')


if __name__ == '__main__':
    main()
