// SPDX-License-Identifier: GPL-2.0-only
/**
 * Place a pre-compiled module (see `native.ts`, generated by tools/aspect/gen_native.py) at its
 * real address. The arithmetic is the same as in that generator, where it is tested against lld.
 */
import { FirmwareError } from '../types';
import { NATIVE } from './native';

export interface LinkedModule {
  code: Uint8Array;
  /** Absolute addresses of the module's exported functions. */
  symbols: Record<string, number>;
}

export function linkNative(name: keyof typeof NATIVE, count: number, origin: number, bindings: Readonly<Record<string, number>>): LinkedModule {
  const mod = NATIVE[name];
  const variant = mod.variants[count];
  if (!variant) throw new FirmwareError('too-many-ratios', `no ${name} module for a count of ${count}`);
  if (origin % 4 !== 0) throw new FirmwareError('internal', 'unaligned module address');
  const values = mod.bindings.map((b) => {
    const v = bindings[b];
    if (v === undefined) throw new FirmwareError('internal', `unbound symbol ${b}`);
    return v >>> 0;
  });
  if (Object.keys(bindings).length !== mod.bindings.length) throw new FirmwareError('internal', `unexpected symbols for ${name}`);
  const raw = Uint8Array.from(atob(variant.code), (c) => c.charCodeAt(0));
  if (raw.length % 4 !== 0) throw new FirmwareError('internal', 'module length');
  const code = raw.slice();
  const dv = new DataView(code.buffer);
  for (const [offset, kind, where, index, addend] of variant.relocs) {
    const symbol = where === 'x' ? values[index] : origin + index;
    const value = (symbol + addend) >>> 0;
    let word = dv.getUint32(offset, true);
    if (kind === 'w' || kind === 't') {
      const imm = kind === 'w' ? value & 0xffff : value >>> 16;
      word = ((word & 0xfff0f000) | ((imm & 0xf000) << 4) | (imm & 0xfff)) >>> 0;
    } else {
      const delta = value - (origin + offset + 8);
      if (delta % 4 !== 0 || !(delta >= -(1 << 25) && delta < 1 << 25)) throw new FirmwareError('internal', 'module branch out of range');
      word = ((word & 0xff000000) | ((delta >> 2) & 0xffffff)) >>> 0;
    }
    dv.setUint32(offset, word, true);
  }
  const symbols: Record<string, number> = {};
  for (const k of Object.keys(variant.exports)) symbols[k] = origin + variant.exports[k];
  return { code, symbols };
}
