# SPDX-License-Identifier: GPL-2.0-only
"""Write core/src/fw/aspect/facts.ts: numbers the reference obtains by running the firmware's own
functions in an emulator (Unicorn). The program has no emulator, so they are recorded here once,
for the one firmware file it accepts (official 1.11, checked by SHA-256 before anything is built).

All values are measurements of that firmware's behaviour: output sizes per quality level and crop
step, the factory ratios' small-image rectangles, the three crop magnifications, the photo-info
rectangle bases, the AE/WB block grid, and whether the quick-view fit fills the screen for each of
the 299 possible screen rectangles.
"""
import json
import struct
from fractions import Fraction

import common
from gr4_editor.crop_native import CropNative
from gr4_editor.crop_state import _MetadataBase
from gr4_editor.crop_raw import _MapProducer
from gr4_editor.crops import _aligned_crop


def screens():
    return [(720, h) for h in range(4, 481, 4)] + [(w, 480) for w in range(4, 720, 4)]


def main():
    img = common.image()
    rows, inspection = common.official_crops()
    assert inspection['native_readback'] == 'passed' and inspection['order'] == [0, 1, 3, 2]
    native = CropNative(img.rtos)

    base_dims = []
    for model in ('Kb588', 'Kb636'):
        mags = native.magnifications(model)
        for selector in range(4):
            for index, mag in enumerate(mags):
                value = native.dimensions(model, 0, mag, selector)
                assert not value['diagnostics']
                base_dims.append([model, selector, index, value['width'], value['height']])

    mags636 = native.magnifications('Kb636')
    mag_bits = [struct.unpack('<I', struct.pack('<f', mag))[0] for mag in mags636]

    factory = []
    for row in sorted(rows, key=lambda item: item['identity']['public_id']):
        geometry = row['geometry']
        full = native.dimensions('Kb636', row['identity']['public_id'], 1.0, 0)
        assert not full['diagnostics']
        factory.append({
            'id': row['identity']['public_id'],
            'textId': row['identity']['text_id'],
            'screen': [geometry['screen'][k] for k in ('left', 'top', 'width', 'height')],
            'thumb': [geometry['thumbnail'][k] for k in ('left', 'top', 'width', 'height')],
            'sizes': sorted({(size['width'], size['height']) for size in geometry['photo_sizes']}),
            'full': [full['width'], full['height']],
        })

    meta = _MetadataBase(img.rtos)
    meta.call(0x537FCC00)
    rect_bases = []
    for mag in mags636:
        pointer = meta.call(0x537FCA6C, float_value=mag)
        assert pointer and not meta.diagnostics
        rect_bases.append(list(struct.unpack('<4I', meta.uc.mem_read(pointer, 16))))

    producer = _MapProducer(img.rtos)
    maps = producer.produce()
    templates = []
    for variant, pointer in enumerate(maps):
        sro = struct.unpack('<I', producer.uc.mem_read(pointer + 0xF0, 4))[0]
        for process in range(4):
            for mag in range(3):
                original = struct.unpack('<I', producer.uc.mem_read(pointer + 4 + (process * 12 + mag) * 4, 4))[0]
                src = struct.unpack('<23H', producer.uc.mem_read(original, 46))
                strips = set()
                for aspect in range(4):
                    address = struct.unpack('<I', producer.uc.mem_read(sro + (process * 12 + aspect * 3 + mag) * 4, 4))[0]
                    strips.add(bytes(producer.uc.mem_read(address, 44)))
                assert len(strips) == 1, 'SRO records differ between factory ratios'
                templates.append([src[3], src[4], src[5], src[6]])

    quick = []
    dims = sorted({(w, h) for _, _, _, w, h in base_dims})
    for width, height in screens():
        actual = Fraction(width, height)
        ok = True
        for bw, bh in dims:
            try:
                region = _aligned_crop(bw, bh, actual)
            except ValueError:
                ok = False
                break
            if native.fit_roi((region['width'], region['height']), (width, height)) != [0, 0, width, height]:
                ok = False
                break
        quick.append(ok)

    facts = {
        'baseDims': base_dims, 'magBits': mag_bits, 'factory': factory, 'rectBases': rect_bases,
        'mapTemplates': templates, 'quickViewFull': ''.join('1' if ok else '0' for ok in quick),
    }
    target = common.REPO / 'core/src/fw/aspect/facts.ts'
    lines = [
        '// SPDX-License-Identifier: GPL-2.0-only',
        '// GENERATED by tools/aspect/gen_facts.py -- do not edit.',
        '//',
        '// Measurements of firmware 1.11 (official fwdc248b.bin, SHA-256 a2f664df...5655f), taken by running',
        "// the firmware's own functions in an emulator the way DoYitNow/gr-custom-tool does. They are only",
        '// valid for that file; the builder checks its SHA-256 first.',
        '',
        '/** Output size for ratio 3:2: [model, quality selector 0..3, crop step 0..2, width, height]. */',
        'export const BASE_DIMS: readonly (readonly [string, number, number, number, number])[] = '
        + json.dumps(base_dims, separators=(',', ':')) + ' as const;',
        '',
        '/** The three crop magnifications of the GR IV as float32 bit patterns (1.0, 1.2524..., 1.7671...). */',
        'export const MAG_BITS: readonly number[] = ' + json.dumps(mag_bits) + ';',
        '',
        '/** Factory ratios by identity 0..3: text id, 720x480 / 160x120 rectangles [left, top, width, height],',
        ' *  every output size they produce, and the full-size GR IV output. */',
        'export const FACTORY: readonly { id: number; textId: number; screen: readonly number[]; thumb: readonly number[]; sizes: readonly (readonly number[])[]; full: readonly number[] }[] = '
        + json.dumps(factory, separators=(',', ':')) + ';',
        '',
        '/** Photo-info rectangle [width, height, left, top] (Q16 on the 45x30 plane) per crop step, ratio 3:2. */',
        'export const RECT_BASES: readonly (readonly number[])[] = ' + json.dumps(rect_bases, separators=(',', ':')) + ';',
        '',
        '/** AE/WB grid templates [block width, block height, blocks across, blocks down]: 3 variants x 4 processes x 3 crop steps. */',
        'export const MAP_TEMPLATES: readonly (readonly number[])[] = ' + json.dumps(templates, separators=(',', ':')) + ';',
        '',
        '/** One character per possible screen rectangle (720 x 4..480 step 4, then 4..716 step 4 x 480):',
        " *  '1' when the firmware's quick-view fit fills that rectangle for every output size. */",
        'export const QUICK_VIEW_FULL = ' + json.dumps(facts['quickViewFull']) + ';',
        '',
    ]
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text('\n'.join(lines), encoding='utf-8')
    print('wrote', target)
    print(json.dumps({k: v for k, v in facts.items() if k not in ('quickViewFull',)}, indent=None)[:3000])
    print(sum(quick), 'of', len(quick), 'screens fit')


if __name__ == '__main__':
    main()
